- name: Deploys VM based on cloud image
  hosts: localhost
  gather_facts: yes
  become: yes
  vars_files:
  - test_vm.yaml
  vars:
    pool_dir: "/var/lib/libvirt/images"
#    vm: {{ vm }}
    vcpus: 2
    ram_mb: 2048
    cleanup: no
    net: br0
    ssh_pub_key: "/home/ansible/.ssh/id_rsa.pub"

  tasks:
    - name: KVM Provision role
      include_role:
        name: kvm_provision
      vars:
        libvirt_pool_dir: "{{ pool_dir }}"
        vm_name: "{{ item }}"
        vm_vcpus: "{{ vcpus }}"
        vm_ram_mb: "{{ ram_mb }}"
        vm_net: "{{ net }}"
        cleanup_tmp: "{{ cleanup }}"
        ssh_key: "{{ ssh_pub_key }}"
      loop: "{{ vms.keys() }}"